"""align warehouse aisle rack models

Revision ID: 3243a76b8247
Revises: 91628d4717a9
Create Date: 2026-08-14 19:28:40.894441

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3243a76b8247'
down_revision: Union[str, None] = '91628d4717a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('aisles', sa.Column('aisle_label', sa.Text(), nullable=False))
    op.add_column('aisles', sa.Column('pos_x', sa.Numeric(), server_default='0', nullable=False))
    op.add_column('aisles', sa.Column('pos_y', sa.Numeric(), server_default='0', nullable=False))
    op.alter_column('aisles', 'direction',
               existing_type=sa.TEXT(),
               nullable=False)
    op.create_unique_constraint('uq_aisle_label_per_warehouse', 'aisles', ['warehouse_id', 'aisle_label'])
    op.drop_column('aisles', 'orientation')
    op.drop_column('aisles', 'code')
    op.add_column('racks', sa.Column('rack_number', sa.Integer(), nullable=False))
    op.add_column('racks', sa.Column('levels', sa.Integer(), server_default='4', nullable=False))
    op.alter_column('racks', 'pos_x',
               existing_type=sa.NUMERIC(),
               nullable=False)
    op.alter_column('racks', 'pos_y',
               existing_type=sa.NUMERIC(),
               nullable=False)
    op.create_unique_constraint('uq_rack_number_per_aisle', 'racks', ['aisle_id', 'rack_number'])
    op.drop_constraint(op.f('racks_warehouse_id_fkey'), 'racks', type_='foreignkey')
    op.drop_column('racks', 'pos_z')
    op.drop_column('racks', 'warehouse_id')
    op.drop_column('racks', 'level_count')
    op.drop_column('racks', 'code')
    op.alter_column('slots', 'pos_x',
               existing_type=sa.NUMERIC(),
               nullable=False)
    op.alter_column('slots', 'pos_y',
               existing_type=sa.NUMERIC(),
               nullable=False)
    op.alter_column('slots', 'pos_z',
               existing_type=sa.NUMERIC(),
               nullable=False)
    op.add_column('warehouses', sa.Column('address', sa.Text(), nullable=True))
    op.create_unique_constraint(None, 'warehouses', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'warehouses', type_='unique')
    op.drop_column('warehouses', 'address')
    op.alter_column('slots', 'pos_z',
               existing_type=sa.NUMERIC(),
               nullable=True)
    op.alter_column('slots', 'pos_y',
               existing_type=sa.NUMERIC(),
               nullable=True)
    op.alter_column('slots', 'pos_x',
               existing_type=sa.NUMERIC(),
               nullable=True)
    op.add_column('racks', sa.Column('code', sa.TEXT(), autoincrement=False, nullable=False))
    op.add_column('racks', sa.Column('level_count', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('racks', sa.Column('warehouse_id', sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('racks', sa.Column('pos_z', sa.NUMERIC(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('racks_warehouse_id_fkey'), 'racks', 'warehouses', ['warehouse_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('uq_rack_number_per_aisle', 'racks', type_='unique')
    op.alter_column('racks', 'pos_y',
               existing_type=sa.NUMERIC(),
               nullable=True)
    op.alter_column('racks', 'pos_x',
               existing_type=sa.NUMERIC(),
               nullable=True)
    op.drop_column('racks', 'levels')
    op.drop_column('racks', 'rack_number')
    op.add_column('aisles', sa.Column('code', sa.TEXT(), autoincrement=False, nullable=False))
    op.add_column('aisles', sa.Column('orientation', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_constraint('uq_aisle_label_per_warehouse', 'aisles', type_='unique')
    op.alter_column('aisles', 'direction',
               existing_type=sa.TEXT(),
               nullable=True)
    op.drop_column('aisles', 'pos_y')
    op.drop_column('aisles', 'pos_x')
    op.drop_column('aisles', 'aisle_label')
    # ### end Alembic commands ###
