"""fix layout_import columns

Revision ID: 91628d4717a9
Revises: d2694ded7ab0
Create Date: 2026-08-14 19:27:07.186234

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '91628d4717a9'
down_revision: Union[str, None] = 'd2694ded7ab0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('layout_imports', sa.Column('filename', sa.Text(), nullable=False))
    op.add_column('layout_imports', sa.Column('raw_content', sa.Text(), nullable=True))
    op.add_column('layout_imports', sa.Column('error_detail', sa.Text(), nullable=True))
    op.add_column('layout_imports', sa.Column('row_count', sa.Integer(), nullable=True))
    op.drop_column('layout_imports', 'file_path')
    op.drop_column('layout_imports', 'validation_errors')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('layout_imports', sa.Column('validation_errors', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('layout_imports', sa.Column('file_path', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_column('layout_imports', 'row_count')
    op.drop_column('layout_imports', 'error_detail')
    op.drop_column('layout_imports', 'raw_content')
    op.drop_column('layout_imports', 'filename')
    # ### end Alembic commands ###
